version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/moviesense
      - JWT_SECRET=your_jwt_secret
      - ML_API_URL=http://ml-api:6000
    depends_on:
      - mongodb
      - ml-api

  ml-api:
    build:
      context: ./ml-api
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./ml-api:/app
    environment:
      - MODEL_PATH=/app/models/sentiment_model.pkl

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 